name: Build for android
on:
  workflow_dispatch:
  push:

jobs:
  build:
    environment: Android
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Set up JDK environment
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    
    - name: Create keystore file
      run: echo "${{ secrets.KEYSTORE }}" | base64 -d > android/key.jks
  
    - name: Build release
      run: bash ./build_android.sh

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Release artifact
        path: android/app/build/outputs/apk/release/*.apk